In [7]:
from fastai.vision.all import *

In [22]:
data = pd.read_pickle('data/iot_all_FE2_5min.pkl')
data.head(2)

,HYDRO_M2-BA-PT-001.MC@MF,HYDRO_M2-DA-PT-001.MC@MF,HYDRO_M2-DPM-GEN-MVAR.MC@MF,HYDRO_M2-DPM-GEN-MW.MC@MF,HYDRO_M2-EXC-001-EI-FIELD.MC@MF,HYDRO_M2-EXC-001-II-FIELD.MC@MF,HYDRO_M2-EXC-001-TI-FIELD-F.MC@MF,HYDRO_M2-GEN-HTX-TE-001-F.MC@MF,HYDRO_M2-GEN-HTX-TE-002-F.MC@MF,HYDRO_M2-GEN-HTX-TE-003-F.MC@MF,...,quarter,is_month_start,is_month_end,is_quarter_start,is_quarter_end,is_year_start,is_year_end,is_leap_year,week,running_time
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
2020-10-18 00:00:00,101.1524,101.1909,0.008785,-0.035158,-0.109869,0.022893,31.77753,78.87299,79.12194,79.54484,...,4.0,False,False,False,False,False,False,True,42.0,1
2020-10-18 00:05:00,100.8747,100.9163,0.008785,-0.035158,-0.109869,0.022893,31.77753,78.90623,79.08869,79.72730,...,4.0,False,False,False,False,False,False,True,42.0,2

In [24]:
print(data.columns)

Index(['HYDRO_M2-BA-PT-001.MC@MF', 'HYDRO_M2-DA-PT-001.MC@MF',
       'HYDRO_M2-DPM-GEN-MVAR.MC@MF', 'HYDRO_M2-DPM-GEN-MW.MC@MF',
       'HYDRO_M2-EXC-001-EI-FIELD.MC@MF', 'HYDRO_M2-EXC-001-II-FIELD.MC@MF',
       'HYDRO_M2-EXC-001-TI-FIELD-F.MC@MF', 'HYDRO_M2-GEN-HTX-TE-001-F.MC@MF',
       'HYDRO_M2-GEN-HTX-TE-002-F.MC@MF', 'HYDRO_M2-GEN-HTX-TE-003-F.MC@MF',
       'HYDRO_M2-GEN-HTX-TE-004-F.MC@MF', 'HYDRO_M2-GEN-LBRG-TE-001-F.MC@MF',
       'HYDRO_M2-GEN-LBRG-TE-002-F.MC@MF', 'HYDRO_M2-GEN-STAT-TE-001.MC@MF',
       'HYDRO_M2-GEN-STAT-TE-003.MC@MF', 'HYDRO_M2-GEN-STAT-TE-006.MC@MF',
       'HYDRO_M2-GEN-STAT-TE-008.MC@MF', 'HYDRO_M2-GEN-STAT-TE-009.MC@MF',
       'HYDRO_M2-GEN-STAT-TE-011.MC@MF', 'HYDRO_M2-GEN-TBRG-TE-001-F.MC@MF',
       'HYDRO_M2-GEN-TBRG-TE-002-F.MC@MF', 'HYDRO_M2-GEN-TBRG-TE-003-F.MC@MF',
       'HYDRO_M2-GEN-TBRG-TE-004-F.MC@MF', 'HYDRO_M2-GEN-TBRG-TE-101-F.MC@MF',
       'HYDRO_M2-GEN-TBRG-TE-102-F.MC@MF', 'HYDRO_M2-GOV-GO-PT-002.MC@MF',
       'HYDRO_M2-GOV-SI-001-SI.MC@MF', 'HYDRO_M2-GOV-SI-002-SI.MC@MF',
       'HYDRO_M2-GOV-WG-OPOS.MC@MF', 'HYDRO_M2-INLETDIS-PT-001.MC@MF',
       'HYDRO_M2-OL-HWL.MC@MF', 'HYDRO_M2-REL-25G-XI-ANGLE.MC@MF',
       'HYDRO_M2-SI-FXD3.MC@MF', 'HYDRO_M2-TE-900-CUR.MC@MF',
       'HYDRO_M2-TURB-HYD-TE-001-F.MC@MF', 'HYDRO_M2-TURB-HYD-TE-002-F.MC@MF',
       'HYDRO_M2_BN_GGB_X_DA.MC@MF', 'HYDRO_M2_BN_GGB_Y_DA.MC@MF',
       'HYDRO_M2_BN_TGB_X_DA.MC@MF', 'HYDRO_M2_BN_TGB_Y_DA.MC@MF',
       'HYDRO_R1-DA-PI-003.R1@RV', 'mode', 'year', 'month', 'day', 'hour',
       'minute', 'second', 'dayofyear', 'dayofweek', 'quarter',
       'is_month_start', 'is_month_end', 'is_quarter_start', 'is_quarter_end',
       'is_year_start', 'is_year_end', 'is_leap_year', 'week', 'running_time'],
      dtype='object')

In [25]:
sensor = ['HYDRO_M2-GEN-TBRG-TE-001-F.MC@MF',
       'HYDRO_M2-GEN-TBRG-TE-002-F.MC@MF', 'mode', 'year', 'month', 'day', 'hour',
       'minute', 'second', 'dayofyear', 'dayofweek', 'quarter',
       'is_month_start', 'is_month_end', 'is_quarter_start', 'is_quarter_end',
       'is_year_start', 'is_year_end', 'is_leap_year', 'week', 'running_time']
temp_data = data[sensor]

In [26]:
temp_data.head(5)

,HYDRO_M2-GEN-TBRG-TE-001-F.MC@MF,HYDRO_M2-GEN-TBRG-TE-002-F.MC@MF,mode,year,month,day,hour,minute,second,dayofyear,...,quarter,is_month_start,is_month_end,is_quarter_start,is_quarter_end,is_year_start,is_year_end,is_leap_year,week,running_time
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
2020-10-18 00:00:00,86.86894,87.93928,off,2020.0,10.0,18.0,0.0,0.0,0.0,292.0,...,4.0,False,False,False,False,False,False,True,42.0,1
2020-10-18 00:05:00,86.84422,87.84802,off,2020.0,10.0,18.0,0.0,5.0,0.0,292.0,...,4.0,False,False,False,False,False,False,True,42.0,2
2020-10-18 00:10:00,86.81938,88.03053,off,2020.0,10.0,18.0,0.0,10.0,0.0,292.0,...,4.0,False,False,False,False,False,False,True,42.0,3
2020-10-18 00:15:00,86.75296,87.88174,off,2020.0,10.0,18.0,0.0,15.0,0.0,292.0,...,4.0,False,False,False,False,False,False,True,42.0,4
2020-10-18 00:20:00,86.90126,87.81381,off,2020.0,10.0,18.0,0.0,20.0,0.0,292.0,...,4.0,False,False,False,False,False,False,True,42.0,5

In [27]:
temp_data.loc[:, 'HYDRO_M2-GEN-TBRG-TE-001-F.MC@MF'] = temp_data['HYDRO_M2-GEN-TBRG-TE-001-F.MC@MF'] - 20
temp_data.loc[:, 'HYDRO_M2-GEN-TBRG-TE-002-F.MC@MF'] = temp_data['HYDRO_M2-GEN-TBRG-TE-002-F.MC@MF'] - 20
temp_data.head(5)

,HYDRO_M2-GEN-TBRG-TE-001-F.MC@MF,HYDRO_M2-GEN-TBRG-TE-002-F.MC@MF,mode,year,month,day,hour,minute,second,dayofyear,...,quarter,is_month_start,is_month_end,is_quarter_start,is_quarter_end,is_year_start,is_year_end,is_leap_year,week,running_time
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
2020-10-18 00:00:00,66.86894,67.93928,off,2020.0,10.0,18.0,0.0,0.0,0.0,292.0,...,4.0,False,False,False,False,False,False,True,42.0,1
2020-10-18 00:05:00,66.84422,67.84802,off,2020.0,10.0,18.0,0.0,5.0,0.0,292.0,...,4.0,False,False,False,False,False,False,True,42.0,2
2020-10-18 00:10:00,66.81938,68.03053,off,2020.0,10.0,18.0,0.0,10.0,0.0,292.0,...,4.0,False,False,False,False,False,False,True,42.0,3
2020-10-18 00:15:00,66.75296,67.88174,off,2020.0,10.0,18.0,0.0,15.0,0.0,292.0,...,4.0,False,False,False,False,False,False,True,42.0,4
2020-10-18 00:20:00,66.90126,67.81381,off,2020.0,10.0,18.0,0.0,20.0,0.0,292.0,...,4.0,False,False,False,False,False,False,True,42.0,5

In [28]:

save_pickle('data/sample_data.pkl', temp_data)